# Generated by Django 3.1.4 on 2021-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210117_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='f_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
