# Generated by Django 3.1.4 on 2021-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210117_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
